apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels: 
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/training-325404/nodeapp-mukul:vVERSION
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-lb
spec:
  selector:            
    app: nodeapp         
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
